### ISSUE TITLE
switch to yarn from npm

### ISSUE THREAD

**Issue by evaneus** [PieLabs/pie-cli#36]
yarn reportedly improves consistency and speed over npm for installing npm packages.

https://yarnpkg.com/

We should look into whether this would bring any near-term benefit for pie-cli.

**Comment by edeustace** [comment]
👍

**Comment by edeustace** [comment]
2 parts to this: 
1. use it as the package manager for `pie-cli`
2. use it as the package manager when executing `pie` commands. Hopefully is has a nice js api to work with, although right now we just `child_process.spawn` so if we had to repeat that it won't ben any worse.

**Comment by edeustace** [comment]
Yarn doesn't have a js api right now (don't know if it's coming or not). Since this issue was created the installation speed has improved alot, so I think that whilst this would be desirable, it's low priority and we should wait and see if yarn release a js api.

see: https://github.com/yarnpkg/yarn/issues/906
