### ISSUE TITLE
Cannot use export loader 

### ISSUE THREAD

**Issue by rbokel** [PieLabs/pie-cli#38]
The support js file below fails with 
```
Error: Module '/home/rbokel/workspace/pie/corespring-line-ng15/docs/demo/node_modules/jsxgraph/distrib/jsxgraphcore.js' is not a loader (must have normal or pitch function)
```
I guess, you are splitting by the exclamation mark without looking out for the question mark? 

```javascript
export function support(dependencies){
  return {
      npmDependencies: {
        'exports-loader' : '^0.6.3'
      },
      webpackLoaders: () => {
      return [
        {
          test: /jsxgraph/,
          loader: 'exports?JXG!jsxgraph/distrib/jsxgraphcore'
        }
      ];
    }
  }
}
```

**Comment by edeustace** [comment]
Yes we are splitting incorrectly - will fix that. However you're also adding a file path to the loader which is not something we handle. We assume that the loader string only specifies the loaders. I'm not sure how I'd be able to check if the last part of the above is a loader or a resource to be processed in this context.

I think that you should probably be using this loader inline - I know they say to avoid it in the docs - but this loader doesn't really fit as a configuration loader because it needs to bind the query to the resource. 

so can you change the above to: 
src: `require('exports?JXG!jsxgraph/distrib/jsxgraphcore');`

support: 
```javascript
export function support(dependencies){
  return {
      npmDependencies: {
        'exports-loader' : '^0.6.3'
      }
  }
}
```

**Comment by rbokel** [comment]
How does webpack parse the loader?

**Comment by edeustace** [comment]
via the `require`

**Comment by rbokel** [comment]
no, i mean, webpack doesn't seem to have a problem parsing the loader declaration

**Comment by edeustace** [comment]
y - but that's because the parse happens within the context of a webpack compilation, in which it's resolved all the available src files + loaders etc. It *may* be possible to use what's in webpack to do the analysis without triggering a failure (aka analyse without trying to compile), but it'll take some poking around the webpack src. Maybe when we have more time we can see if there's something in there we can use.

**Comment by rbokel** [comment]
is it failing in our code or in webpack? i thought it is in our duplicate loaders logic?

**Comment by edeustace** [comment]
Actually - this is most likely a webpack issue - not pie-cli - going to confirm shortly.

**Comment by edeustace** [comment]
This is definitely an issue with how we are trying to use: [webpack/exports-loader](webpack/exports-loader). I think it can only really be used inline as suggested above. 
Closing the issue.
