### ISSUE TITLE
legacy framework support: external js and css 

### ISSUE THREAD

**Issue by rbokel** [PieLabs/pie-cli#58]
For MathJax i'd need the option to add script tags and/or styles to the generated html 
We could extend the legacy-framework to have  
{externals: { js: [], css: [] }

**Comment by edeustace** [comment]
Note that this is not something we're going to publicise as an option and the sooner we can remove it the better because it breaks the idea of building a single bundle to use when running an item. However if any 3rd parties want to use an item with corespring legacy components they'll need to remember to add mathjax themselves to their markup.

**Comment by rbokel** [comment]
done
